spring.application.name=PlayZoneAPI

# --- Datasource ---
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://127.0.0.1:5432/playzonebd}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgresueb}

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=${JPA_DDL:validate}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Flyway ---
spring.flyway.enabled=${FLYWAY_ENABLED:true}
spring.flyway.clean-disabled=true
spring.flyway.baseline-on-migrate=true

# --- Server ---
server.port=${PORT:8080}
server.address=0.0.0.0

# --- JWT ---
application.security.jwt.secret-key=${JWT_SECRET:clavelargaquetienequeusarseacayvamosausarparaplayzone1234567890}
application.security.jwt.expiration=86400000

# --- Correo ---
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:jgarzon424@gmail.com}
spring.mail.password=${MAIL_PASSWORD:uzim uwhz mpwd xvkw}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8

# --- Mercado Pago ---
mercadopago.access-token=${MP_ACCESS_TOKEN:APP_USR-2107691743785423-031011-828e544adabf7bdf7fb0983e98e34039-3257117728}
app.base-url=${APP_BASE_URL:https://1b7a-200-91-211-174.ngrok-free.app}